services:

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: pass
      APP_USER: emp_mngr
      APP_USER_PASSWORD: mypwd
    volumes:
      - ./oracle-data:/opt/oracle/oradata
    networks:
      - backend

  employee-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: employee-web
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      DB_URL: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
    networks:
      - backend

volumes:
  oracle-data:

networks:
  backend:
